import { NextRequest, NextResponse } from 'next/server'
import { requireRole, getUserFromRequest } from '@/lib/auth'
import { createMemory, listMemory } from '@/lib/working-memory'
import { z } from 'zod'

const input = z.object({ project_id:z.string().nullable().optional(), agent_id:z.string().nullable().optional(), task_id:z.string().nullable().optional(), memory_type:z.enum(['current_state','handoff','task_outcome','recent_decision','incident_context','product_context','operational_note','blocker','lesson_candidate','promotion_candidate']), scope:z.enum(['tenant/company','project','agent','task']), title:z.string(), content:z.string(), source:z.string(), importance:z.enum(['low','normal','high','critical']), durable_reference:z.string().nullable().optional(), expires_at:z.number().int().positive().nullable().optional(), metadata:z.record(z.string(),z.union([z.string(),z.number(),z.boolean(),z.null()])).optional(), lifecycle_status:z.enum(['active','superseded','resolved','expired','archived']).optional(), promotion_status:z.enum(['none','promotion-candidate','promoted']).optional() }).strict()
function auth(request: NextRequest, role: 'viewer'|'operator') { const result=requireRole(request,role); if ('error' in result) return NextResponse.json({error:result.error},{status:result.status}); const user=getUserFromRequest(request); if(!user) return NextResponse.json({error:'Authentication required'},{status:401}); return user }
export async function GET(request: NextRequest) { const user=auth(request,'viewer'); if(user instanceof NextResponse) return user; try { const p=request.nextUrl.searchParams; const query:any={}; for(const key of ['memory_id','project_id','agent_id','task_id','memory_type','importance','lifecycle_status','promotion_status','source'] as const) if(p.has(key)) query[key]=p.get(key); if(p.has('recency_since')) query.recency_since=Number(p.get('recency_since')); if(p.has('limit')) query.limit=Number(p.get('limit')); if(p.has('offset')) query.offset=Number(p.get('offset')); return NextResponse.json({ memories:listMemory(user,query,p.get('tenant_key')) }) } catch(e) { return NextResponse.json({error:e instanceof Error?e.message:'Memory query failed'},{status:403}) } }
export async function POST(request: NextRequest) { const user=auth(request,'operator'); if(user instanceof NextResponse) return user; try { const body=input.parse(await request.json()); return NextResponse.json({memory:createMemory(user,body,request.nextUrl.searchParams.get('tenant_key'))},{status:201}) } catch(e) { return NextResponse.json({error:e instanceof z.ZodError?'Invalid memory payload':e instanceof Error?e.message:'Memory creation failed'},{status:e instanceof z.ZodError?400:403}) } }
